### ISSUE TITLE
Link to database file is down

### ISSUE THREAD

**Issue by 7PintsOfCherryGarcia** [snayfach/MIDAS#109]
Link to the database file is unfortunately now working. Any workaround other than building the database myself? 

![donw](https://user-images.githubusercontent.com/42513628/85149238-57010080-b251-11ea-89ba-01eb8d75a20e.png)

**Comment by Steffireise** [comment]
Is there any notion on when or whether the database will be accessible again?

**Comment by tjcu408** [comment]
when the database will be accessible again?

**Comment by pbradz** [comment]
If you click the link, it now redirects to a Dropbox page where the database is stored.

**Comment by 7PintsOfCherryGarcia** [comment]
Awesome thanks!!
