### ISSUE TITLE
Request for information on how are marker genes chosen in custom database ?

### ISSUE THREAD

**Issue by Aiswarya-prasad** [snayfach/MIDAS#131]
I am using midas on my custom database comprising my own MAGs. It is not clear to me what criteria are used to select marker genes. Is it just that they should be core (present in all MAGs) of a given species? Are there any relaxations or further contraints to this?

**Comment by snayfach** [comment]
The marker genes are listed here: https://github.com/snayfach/MIDAS/blob/master/midas/build/phyeco.hmm and described in the paper. They are a list of 15 universally distributed, single copied, protein coding gene families. Let me know if you run into any issues with the database building.

**Comment by snayfach** [comment]
I should add - those 15 genes are identified in the genomes you provide as input.

**Comment by Aiswarya-prasad** [comment]
Is this done in a data-dependent way? Meaning that the same genes be searched for in any genome or are they 15 genes that happen to be in the given database? I also find that there is a different number of marker genes for each species-id group.

**Comment by snayfach** [comment]
Each of the 15 genes is represented by a profile HMM and those HMMs are
what's searched against a new genome when you do a custom database. All 15
should be found in any new bacterial/archaeal genome, provided they are
near-complete.
