### ISSUE TITLE
Population diversity with intermediate frequency

### ISSUE THREAD

**Issue by azk001** [snayfach/MIDAS#132]
Hi,

I'm looking for within-sample polymorphism with allele frequencies between 0.2 and 0.8.
However, I noticed that MIDAS has two choices for the minimum frequency: --snp_maf and --site_maf. I'm not sure which one to use and how I can set it from 0.2 to 0.8.

Thank you!

Amanpreet.

**Comment by snayfach** [comment]
Use --snp_maf. The site frequency flag requires the location to have coverage in a minim % of your samples.
