### ISSUE TITLE
Failed to execute the command: merge_midas.py genes error

### ISSUE THREAD

**Issue by liyun831229** [snayfach/MIDAS#20]
I just installed MIDAS and runed python test_midas.py -f
I got the following error:
python test_midas.py -f
./home/qiime/anaconda3/lib/python3.5/site-packages/boto/plugin.py:40: PendingDeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
.F
======================================================================
FAIL: test_help_text (__main__.MergeGenes)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_midas.py", line 92, in test_help_text
    self.assertTrue(sum(self.retcodes)==0, msg=error)
AssertionError: False is not true : 

Failed to execute the command: merge_midas.py genes 

----------------------------------------------------------------------
Ran 3 tests in 1.984s

FAILED (failures=1)

**Comment by snayfach** [comment]
Hi liyun,

I have not extensively tested MIDAS using Python3. Could you see if it works using Python2? In the meantime I will work on compatibility with Python2

Stephen

**Comment by snayfach** [comment]
MIDAS is now python3 compatible. Could you please install the latest version and try the unit test again?

**Comment by kilaza** [comment]
Hello, 
Kindly assist, I have just installed MIDAS. I am getting an error when testing (test_midas.py -vf). The error complains about the bowtie2. I have tried all the options given but still, I can not make it. Thanks in davance.

here is the error
[kmwaikono@cluster test]$ ./test_midas.py -vf
test_class (__main__._01_CheckEnv) ... ok
test_class (__main__._02_ImportDependencies) ... /home/kmwaikono/miniconda3/lib/python3.6/importlib/_bootstrap.py:219: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
  return f(*args, **kwds)
/home/kmwaikono/miniconda3/lib/python3.6/importlib/_bootstrap.py:219: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
  return f(*args, **kwds)
ok
test_class (__main__._03_CheckVersions) ... ok
test_class (__main__._04_HelpText) ... ok
test_class (__main__._05_RunSpecies) ... FAIL

======================================================================
FAIL: test_class (__main__._05_RunSpecies)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./test_midas.py", line 90, in test_class
    self.assertTrue(code==0, msg=err)
AssertionError: False is not true : b'\nError: could not execute samtools binary: /home/kmwaikono/desktop/metagenomics/MIDAS/bin/Linux/samtools\n(exited with error code 127)\nTo solve this issue, follow these steps:\n  1) Download samtools v1.4: https://github.com/samtools/samtools/releases/download/1.4/samtools-1.4.tar.bz2\n  2) Unpack and compile the software on your system\n  3) Copy the new samtools binary to: /home/kmwaikono/desktop/metagenomics/MIDAS/bin/Linux\n\n'
