### ISSUE TITLE
return "permission denied" after install MIDAS in sever 

### ISSUE THREAD

**Issue by liyun831229** [snayfach/MIDAS#21]
Hi,
I sucessfully installed MIDAS in my local PC, I do not get any error when I runed "run_midas.py". However, after I installed it in a cluster  sever with --prefix='/.local' option, I get 'permission denied' error when I runned "run_midas.py". Anything was wrong?

**Comment by snayfach** [comment]
I'm not sure. Does the test run successfully? Could you send me the full
command and error message?

**Comment by liyun831229** [comment]
Hi,
Now I can install the MIDAS sucessfully into server. However, When I tried to run the test file I got the following error.
[???@??? test]$ python test_midas.py
....FFFFFF
======================================================================
FAIL: test_help_text (__main__.MergeGenes)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_midas.py", line 128, in test_help_text
    self.assertTrue(sum(self.retcodes)==0, msg=error)
AssertionError:

Failed to execute the command: merge_midas.py genes

======================================================================
FAIL: test_help_text (__main__.MergeSNPs)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_midas.py", line 138, in test_help_text
    self.assertTrue(sum(self.retcodes)==0, msg=error)
AssertionError:

Failed to execute the command: merge_midas.py snps

======================================================================
FAIL: test_help_text (__main__.MergeSpecies)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_midas.py", line 118, in test_help_text
    self.assertTrue(sum(self.retcodes)==0, msg=error)
AssertionError:

Failed to execute the command: merge_midas.py species

======================================================================
FAIL: test_help_text (__main__.RunGenes)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_midas.py", line 100, in test_help_text
    self.assertTrue(run(self.command)==0, msg=error)
AssertionError:

Failed to execute the command: run_midas.py genes ./sample -1 ./test.fq.gz -n 100 --                                             species_id 57955

======================================================================
FAIL: test_help_text (__main__.RunSNPs)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_midas.py", line 108, in test_help_text
    self.assertTrue(run(self.command)==0, msg=error)
AssertionError:

Failed to execute the command: run_midas.py snps ./sample -1 ./test.fq.gz -n 100 --s                                             pecies_id 57955

======================================================================
FAIL: test_help_text (__main__.RunSpecies)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_midas.py", line 92, in test_help_text
    self.assertTrue(run(self.command)==0, msg=error)
AssertionError:

Failed to execute the command: run_midas.py species ./sample -1 ./test.fq.gz -n 100

----------------------------------------------------------------------
Ran 10 tests in 3.919s

**Comment by liyun831229** [comment]
When I run run_midas.py species ./sample -1 ./test.fq.gz -n 100 alone, it shows that error:
_Could not locate reference database: /home/yunli1/Biosoftware/MIDAS-master/ref_db_
how to set up the ref_db

**Comment by liyun831229** [comment]
When I run "run_midas.py species ./sample -1 ./test.fq.gz -n 100" alone. It shows the following error:
_Could not locate reference database: /PATH/TO/MIDAS-master/ref_db_
How to setup the ref_db?

**Comment by snayfach** [comment]
You need to run the `download_ref_db.py` script

Also, I've made a few improvements to the code since you first reported an error on Aug 26. I'd recommend pulling the latest version of the code: `cd /path/to/MIDAS; git pull`

And try to rerun the test code: `cd /path/to/MIDAS/test; python test_midas.py`

**Comment by liyun831229** [comment]
Thanks snayfach,
How to avoid running the dowload script? I am working on a server with no web access to the outside world. or can I just run the dowload script in the local machine and copy the downloaded file into server?

**Comment by snayfach** [comment]
Yes, run the download script on a local machine. After it's finished downloading and unpacking, copy `/path/to/MIDAS/ref_db` to the MIDAS directory on your remote server
