### ISSUE TITLE
run_midas.py snps produces no PileUp file

### ISSUE THREAD

**Issue by alexhbnr** [snayfach/MIDAS#38]
At the current commit, running the tutorial with the examples fails when running:
`run_midas.py snps midas_output/sample_1 -1 example/sample_1.fq.gz`

The script complains that no pileup file can be open when trying to format the mpileup output. It seems that the reason for the missing mpileup file is that the function call to generate it is commented out in snps.py [line 288](https://github.com/snayfach/MIDAS/blob/master/midas/run/snps.py#L288). 

When I remove the comment, the example runs through without any troubles.

**Comment by snayfach** [comment]
Thanks for catching this. It should be fixed now.
