### ISSUE TITLE
compare_genes.py vs. gene_sharing.py

### ISSUE THREAD

**Issue by alexhbnr** [snayfach/MIDAS#39]
There is an inconsistency in the naming of the script regarding the gene content analysis. In the [documentation](https://github.com/snayfach/MIDAS/blob/master/docs/compare_genes.md), the script is named  _gene_sharing.py_, while both the script and the documentation markdown document are named _compare_genes.py_ and _compare_genes.md_, respectively.

One should either fix the documentation or rename the files accordingly.

**Comment by snayfach** [comment]
This has been fixed. Please let me know if you find any other issues.
