### ISSUE TITLE
Missing species in MIDAS

### ISSUE THREAD

**Issue by fplaza** [snayfach/MIDAS#44]
Hi,
First of all, thank you for publishing MIDAS.
I was wondering why _Methanobrevibacter smithii_ has no representative genomes.
It appears in _genome_taxonomy.txt_ but not in _genome_taxonomy.txt_
Thank for your help

**Comment by fplaza** [comment]
I just realized that you only keep bacterial species.
Why don't you include archea?

**Comment by snayfach** [comment]
Hi Florian,

Archaea will be included in the next version of the database, but that
might not be ready for a few months.

Best,
Stephen

**Comment by fplaza** [comment]
Thank you for answering.
I will add them manually then.

**Comment by snayfach** [comment]
Florian,

Please note that many of the marker genes used in`run_midas.py species` are only found in bacteria. So you will likely underestimate the abundance of archaea. These genes are also used for normalization (i.e. computing gene copy numbers) in `run_midas.py genes`. There will not be any issues with `run_midas.py snps`. These issues will be addressed in a future version of the software. Let me know if you need any suggestions on how to work around the issues in the interim.

Best,
Stephen
