### ISSUE TITLE
query_coverage requires obscure format

### ISSUE THREAD

**Issue by JeremyHorst** [snayfach/MIDAS#45]
Thank you for this wonderful tool. My test runs failed due to the requirement of species.py function query_coverage for the sequence header to end in "_" followed by the length of the sequence. I understand that m8 output format does not give the length of the hit sequence, but what the function requires is non-standard for FASTA or FASTQ and will be an impediment to most users. Please figure out another way to do this. I wrote a stupid python script to do so for FASTA (below); the analogy is easy for FASTQ. I don't think this is a good solution because it produces redundant very large files, and neither is it a good solution to edit user's original files. It may be best to grep out the line from the FASTA (or 3rd from the FASTQ) following the hit sequence header, measure the length.

```
#/usr/bin/python
from sys import argv
f=open(argv[1])
line1 = f.readline().strip()
line2 = f.readline().strip()
while line1:
	print line1.split()[0]+'_'+str(len(line2))
	print line2
	line1 = f.readline().strip()
	line2 = f.readline().strip()
```

**Comment by snayfach** [comment]
Hi Jeremy,

Could you please provide the command you used and the error? It might also be helpful if you could provide a small dataset that causes the error. With this, I should be able to track down the issue.

To address your comment, input FASTA/FASTQ files do not need to be in any special format. The formatting (and addition of read length in the sequence header) is built into the program and is executed by the script: https://github.com/snayfach/MIDAS/blob/master/midas/run/stream_seqs.py

Best,
Stephen

**Comment by JeremyHorst** [comment]
For example, this sequence gets a hit & induces an error:
>K00153:243:HHFJVBBXX:7:1111:1834:2598/1	00
GCGCTTAGCAAAGTGACGTGTATTCTTCTTAATTAAGTCACGACACTCATCTAATGTTATATTGCCATTTATATAGTCTACAACCTCTTTACAGCCAATACCTTTAAAAGCTTGGCAATCTGGATT

using this command:
run_midas.py species ../midas-out/tmp1/ -1 tmp1.fasta

Below is the error message:

MIDAS: Metagenomic Intra-species Diversity Analysis System
version 1.2.1; github.com/snayfach/MIDAS
Copyright (C) 2015-2016 Stephen Nayfach
Freely distributed under the GNU General Public License (GPLv3)

===========Parameters===========
Command: /data/lactobacillus//bin/MIDAS/scripts/run_midas.py species ../midas-out/tmp1/ -1 tmp1.fasta
Script: run_midas.py species
Database: /data/lactobacillus//bin/MIDAS/midas_db_v1.2
Output directory: ../midas-out/tmp1/
Input reads (1st mate): tmp1.fasta
Input reads (2nd mate): None
Remove temporary files: False
Word size for database search: 28
Minimum mapping alignment coverage: 0.75
Number of reads to use from input: use all
Number of threads for database search: 1
================================

Aligning reads to marker-genes database
  0.02 minutes
  0.71 Gb maximum memory

Classifying reads
Traceback (most recent call last):
  File "/data/lactobacillus//bin/MIDAS/scripts/run_midas.py", line 699, in <module>
    run_program(program, args)
  File "/data/lactobacillus//bin/MIDAS/scripts/run_midas.py", line 75, in run_program
    species.run_pipeline(args)
  File "/data/lactobacillus/bin/MIDAS/midas/run/species.py", line 248, in run_pipeline
    best_hits = find_best_hits(args, marker_info)
  File "/data/lactobacillus/bin/MIDAS/midas/run/species.py", line 76, in find_best_hits
    elif query_coverage(aln) < args['aln_cov']: # filter local alignments
  File "/data/lactobacillus/bin/MIDAS/midas/run/species.py", line 62, in query_coverage
    return float(aln['aln'])/int(qlen)
ValueError: invalid literal for int() with base 10: 'K00153:243:HHFJVBBXX:7:1111:1834:2598/1'

**Comment by JeremyHorst** [comment]
btw - I did notice that the script works if I remove the "/t00" at the end of each title line, but again, I highly recommend not having anything dependent on users being conformist to some non-existent standard with their FASTA/Q title lines.

**Comment by snayfach** [comment]
Thanks for the info. I get the same error with your sequence. I should have a fix soon. And I agree that the program should work on any FASTA/FASTQ file with the standard format

**Comment by snayfach** [comment]
The issue should be solved now. Please reopen the issue as necessary. Thanks for finding the bug!

**Comment by JeremyHorst** [comment]
Thanks Stephen, you're the man! Hope to meet you some time. I'm actually coming to your lab tomorrow to get some help from Svetlana.

Peace and thanks,
Jeremy from the DeRisi lab

**Comment by JeremyHorst** [comment]
Thank you - perfect!

**Comment by snayfach** [comment]
You're welcome! Let me know if you find other bugs or have any feature requests.

Stephen
