### ISSUE TITLE
Error when using run_midas for genes

### ISSUE THREAD

**Issue by WillPascucci** [snayfach/MIDAS#46]
Hi, Thank you very much for your tool. I was using it on a fastq file I have and successfully ran the species function, however, when I ran the genes function I got the following error (after 6 hours of it running successfully)
`
MIDAS: Metagenomic Intra-species Diversity Analysis System
version 1.2.1; github.com/snayfach/MIDAS
Copyright (C) 2015-2016 Stephen Nayfach
Freely distributed under the GNU General Public License (GPLv3)

Parameters
Command: ./MIDAS/scripts/run_midas.py genes ./data_out/poolA_res/ -1 ../FASTQ_Files/poolA_S17_L005_R1_001.fastq
Script: run_midas.py genes
Database: midas_db_v1.2
Output directory: ./data_out/poolA_res/
Remove temporary files: False
Pipeline options:
  build bowtie2 database of pangenomes
  align reads to bowtie2 pangenome database
  quantify coverage of pangenomes genes
Database options:
  include all species with >=3.0X genome coverage
Read alignment options:
  input reads (1st mate): ../FASTQ_Files/poolA_S17_L005_R1_001.fastq
  input reads (2nd mate): None
  alignment speed/sensitivity: very-sensitive
  number of reads to use from input: use all
  number of threads for database search: 1
Gene coverage options:
  minimum alignment percent identity: 94.0
  minimum alignment coverage of reads: 0.75
  minimum read quality score: 20
  minimum mapping quality score: 0
  trim 0 base-pairs from 3'/right end of read

Reading reference data
  0.56 minutes
  0.2 Gb maximum memory

Building pangenome database
  total species: 11
  total genes: 576240
  total base-pairs: 497291760
  33.44 minutes
  1.16 Gb maximum memory

Aligning reads to pangenomes
  finished aligning
  checking bamfile integrity
  293.88 minutes
  1.16 Gb maximum memory

Computing coverage of pangenomes
  total aligned reads: 29207158
  total mapped reads: 22242407
Traceback (most recent call last):
  File "./MIDAS/scripts/run_midas.py", line 699, in <module>
    run_program(program, args)
  File "./MIDAS/scripts/run_midas.py", line 78, in run_program
    genes.run_pipeline(args)
  File "/Users/williampascucci/Documents/Research/MIDAS/MIDAS/midas/run/genes.py", line 274, in run_pipeline
    pangenome_coverage(args, species, genes)
  File "/Users/williampascucci/Documents/Research/MIDAS/MIDAS/midas/run/genes.py", line 151, in pangenome_coverage
    normalize(args, species, genes)
  File "/Users/williampascucci/Documents/Research/MIDAS/MIDAS/midas/run/genes.py", line 201, in normalize
    sp.marker_coverage = np.median(sp.markers.values())
  File "//anaconda/lib/python3.5/site-packages/numpy/lib/function_base.py", line 3944, in median
    overwrite_input=overwrite_input)
  File "//anaconda/lib/python3.5/site-packages/numpy/lib/function_base.py", line 3858, in _ureduce
    r = func(a, **kwargs)
  File "//anaconda/lib/python3.5/site-packages/numpy/lib/function_base.py", line 4002, in _median
    return mean(part[indexer], axis=axis, out=out)
  File "//anaconda/lib/python3.5/site-packages/numpy/core/fromnumeric.py", line 2889, in mean
    out=out, **kwargs)
  File "//anaconda/lib/python3.5/site-packages/numpy/core/_methods.py", line 82, in _mean
    ret = ret / rcount
TypeError: unsupported operand type(s) for /: 'dict_values' and 'int'`

I am not sure where I am going wrong, thank you for any help you can provide!

**Comment by snayfach** [comment]
Hi Will,

I think this is an issue with python 3.5; most testing was done on python 2.7. I can look into fixing the issue, but in the meantime you can try running MIDAS with a version of python 2. 

Best,
Stephen

**Comment by WillPascucci** [comment]
Thanks!

**Comment by snayfach** [comment]
Hi Will,

I just committed some code that fixes the bug you found when running MIDAS with python3. Could you pull and see if it works for you? I don't have python3 set up right now on my system, so there's a chance that you may find another python3-specific bug.

Thanks,
Stephen

**Comment by WillPascucci** [comment]
Hi, it worked, thank you for the fix!
