### ISSUE TITLE
Result Inquiry

### ISSUE THREAD

**Issue by WillPascucci** [snayfach/MIDAS#48]
Hi (Thanks again for your software),
In regards to the output of the read mapping. For the output for each species/strain in the .genes file, are adjacent id's (ie. 1182695.3.peg.1168, 1182695.3.peg.1169, 1182695.3.peg.1170) corresponding to adjacent positions on the genome of the species? If so we were examining the results of the read mapping to pangenomes for a few samples, we saw several cases where one position had thousands of read mapped to it but an adjacent position would have no reads. We thought that was a little odd in comparison to most other positions where several adjacent positions would have smoothly distributed reads.
Had you experienced any similar cases/results? If so, did you have any methods for accounting for those cases?
Thanks!

**Comment by snayfach** [comment]
Hey Will,

First off, those are PATRIC gene ids. The MIDAS database contains a subset of the rich metadata and file types provided by PATRIC. So, if you want extra information not in the MIDAS db (like genomic coordinates of genes), try checking out PATRIC: 
https://www.patricbrc.org and ftp://ftp.patricbrc.org/patric2

I can make that info available in a future release. In the meantime, I've attached the genomic coordinates of genes for the genome `1182695.3` which is the only member of the species `Klebsiella_pneumoniae_546881`. From the file you can see that, yes, 1182695.3.peg.1168, 1182695.3.peg.1169, 1182695.3.peg.1170 corresponding to adjacent genes on the genome.

The annotations of those genes are: `Unknown pentose isomerase TM0951`, `Transketolase, C-terminal section (EC 2.2.1.1)`, and `Transketolase, N-terminal section (EC 2.2.1.1)`. It is a bit surprising that the C and N-terminal sections have different results. Have you looked at multiple metagenomes, and if so, do you see the same pattern?

You can also try looking at the results of run_midas.py snps, where you will be able to visualize the per-bp read-depth across the representative genome.

[1182695.3.gene_info.txt]

(https://github.com/snayfach/MIDAS/files/870845/1182695.3.gene_info.txt)

**Comment by WillPascucci** [comment]
Hi,
Thank you for your reply. We did see the same pattern on two samples on multiple species. We ran a rough algorithm for tracking high-read adjacent to low-read positions and found a few instances in the instances. It seemed to be more prevalent in less represented species and less prevalent in species with a large number of mappings. We were wondering if you had any idea on how that could happen?

I also had a question regarding the same results (excerpt below for reference). In looking at the results, there are genes at 1220, 1221, 1224, and 1229, but nothing at the genes in between (1222-1223,1225-1228). However, at many of the positions that were included we saw 0's and were wondering what the significance of an excluded gene vs. a 0-read gene was. Thanks for your help!

1182695.3.peg.1220      0       0.0     0.0
1182695.3.peg.1221      3057    197.10043290042785      0.368538020017
1182695.3.peg.1224      696     88.20767888307216       0.16493055265
1182695.3.peg.1229      0       0.0     0.0

Best,
Will

**Comment by snayfach** [comment]
Hi Will,

The genes in the database have been clustered at 99% DNA identity. Each gene that appears in the output is a centroid for one gene cluster. So if a gene is "missing" from the output, it means that it has been assigned to a gene cluster, but is not the centroid for that cluster. Check out this link for more info: http://drive5.com/usearch/manual/uclust_algo.html

When you run the merge step for MIDAS (merge_midas.py genes), you can specify the % identity cutoff you want to use for defining gene families. I believe the default value is 95%. When you look at the per sample output as shown in your example (run_midas.py genes) the default value is 99%.

If you're interested in the mappings between genes (i.e. which genes are assigned to which gene clusters) look at the database file: pan_genomes/<species_id>/gene_info.txt.gz. You can look at the README for more info as well: http://lighthouse.ucsf.edu/MIDAS/README.txt

So, in your example, it appears that genes 1220 and 1229 are absent from the population in your metagenome and genes 1221 and 1224 are present (in at least in a subset of the population). Genes 1222, 1223, and 1225-1228 have been assigned to a gene cluster.

Hope this helps.

Best,
Stephen
