### ISSUE TITLE
Sample depth parameter for CNV merging

### ISSUE THREAD

**Issue by ngarud** [snayfach/MIDAS#49]
Hi Stephen,

I'm confused how --sample-depth works for CNV merging. Suppose I set the sample-depth to be 10, but there is only one gene that doesn't meet this requirement. Does that one gene's lack of coverage mean that we throw out the whole sample? Or is it just that gene that is removed?  

Thanks,
Nandita

**Comment by snayfach** [comment]
--sample-depth is an option to exclude samples from the gene content matrix. It excludes samples with an average depth less than the value specified by the --sample-depth flag. The average depth is calculated across all genes with at least 1 mapped read.

**Comment by ngarud** [comment]
Thanks, I understand.
Nandita
