### ISSUE TITLE
How is genes_depth.txt computed?

### ISSUE THREAD

**Issue by ngarud** [snayfach/MIDAS#50]
Hi Stephen,

I was wondering if you could help answer a question about genes_depth.txt. I'm trying to figure out how exactly depth (or, coverage in the field below) is computed for each gene. I have pasted an example case below for a sample from the HMP and the corresponding MIDAS output for the genes (pre-merge format). 

sample ID=700015181
numbp=570 (obtained from the pangenome for B. uniformis)

gene_id    count_reads    coverage    copy_number
1235787.3.peg.10    25    4.33859649123    0.0168362540388

I went through count_mapped_bp def in genes.py and I'm guessing that you divide the number of aligned bps by the total number of bps in a gene to get coverage. Is this correct?

genes[gene_id].depth += aln_len/float(gene_len)

Is count_reads the total number of reads aligning to a gene, regardless of where in the gene it aligns (i.e. if only part of a read aligns to the gene and the other part is hanging over covering a neighboring gene, is this read still counted in count_reads)?

Thanks,
Nandita

**Comment by snayfach** [comment]
Your formula for coverage (or depth) is correct. 

Each metagenomic read is assigned to 1 gene max. Read assignments are determined by the percent identity and alignment coverage parameters in `run_midas.py genes`. Use `run_midas.py genes -h` for more info. And yes, count_reads is the total number of reads assigned to a gene.
