### ISSUE TITLE
Building custom database - input file formats?

### ISSUE THREAD

**Issue by ewilbanks** [snayfach/MIDAS#51]
Hey Stephen,

I'm working with my students to give your software a whirl and had a question about building a custom database.  In your description of input files, we had a question about file formats & content:

> <genome_id>.fna Genomic DNA sequence in FASTA format
> <genome_id>.faa Genomic DNA sequence in FASTA format
> <genome_id>.ffn Protein sequences in FASTA format

Should the .faa file be the coding sequences (in amino acids) and the .ffn be coding sequences in nucleic acids?  I wasn't sure if there might be a type in your instructions above...

Also - if we have only one genome per species, are there any other considerations we should keep in mind or will it simply skip the pangenome step for a species with a single genome (as reference din the mapfile)?

Thanks!
Lizzy

**Comment by snayfach** [comment]
Hi Lizzy,

It can still be informative to run the pangenome-mapping step even if you have just one genome. Here are some cool analysis you might be able to do: 
-look at how genes in the reference genome co-vary in presence/absence across metagenomes
-perform PCA on the gene content matrix to uncover population structure
-identify core gene and variable genes with just a single reference

And thanks for catching the typo. The documentation now reads:
```
<genome_id>.fna Genomic DNA sequence in FASTA format
<genome_id>.faa Protein sequences in FASTA format
<genome_id>.ffn Gene sequences in FASTA format
```

Best,
Stephen

**Comment by ewilbanks** [comment]
Thanks Stephen!

**Comment by feltzmc** [comment]
Hi Lizzy (@ewilbanks) ,

Did you get the custom database to work?  I am having issues with the feature file reader saying that my column "gene_id" does not exist.  Stephen (@snayfach) you are welcome to jump in as well.

My feature file looks like this:
gene_id	scaffold_id	start	end	strand	gene_type
2906259	GCF_000002525.2	2659	5277	+	gene
2906259	GCF_000002525.2	2659	5277	+	mRNA
2906259	GCF_000002525.2	2659	5277	+	CDS
2906265	GCF_000002525.2	7045	8880	+	gene
2906265	GCF_000002525.2	7045	8880	+	mRNA
2906265	GCF_000002525.2	7045	8880	+	CDS

Thanks,
Matt

**Comment by snayfach** [comment]
Hey Matt,

Are you running the latest version of MIDAS? Have you tried running the test code `MIDAS/test/test_midas.py`? 

There are also some example database files in the test directory that should help: `test/genomes.mapfile` and `test/genomes.tar.gz`. After unpacking the genomes directory, you can see what database file should look like:
```
cd MIDAS/test
tar -zxvf genomes.tar.gz
ls genomes
```

For the gene_type field, I would recommend CDS for protein coding genes and RNA for non-coding genes.

Best,
Stephen

**Comment by feltzmc** [comment]
Thank you for the quick response Stephen!

I will double check to make sure I am running the most recent version, just downloaded it in July but you seem to be a very active developer.  

I did notice that the genes files I downloaded from Refseq for these organisms label some genes multiple times as gene, mRNA, and CDS.  I can probably come up with a script to fix those.  I will also take a look at the example file as you have suggested.

I have been able to run analyses on some files I have successfully but when I ran test_midas.py 6/10 tests failed:

python test_midas.py
....FFFFFF
======================================================================
FAIL: test_help_text (__main__.MergeGenes)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_midas.py", line 133, in test_help_text
    self.assertTrue(sum(self.retcodes)==0, msg=error)
AssertionError:

Failed to execute the command: merge_midas.py genes

======================================================================
FAIL: test_help_text (__main__.MergeSNPs)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_midas.py", line 143, in test_help_text
    self.assertTrue(sum(self.retcodes)==0, msg=error)
AssertionError:

Failed to execute the command: merge_midas.py snps

======================================================================
FAIL: test_help_text (__main__.MergeSpecies)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_midas.py", line 123, in test_help_text
    self.assertTrue(sum(self.retcodes)==0, msg=error)
AssertionError:

Failed to execute the command: merge_midas.py species

======================================================================
FAIL: test_help_text (__main__.RunGenes)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_midas.py", line 105, in test_help_text
    self.assertTrue(run(self.command)==0, msg=error)
AssertionError:

Failed to execute the command: run_midas.py genes ./sample -1 ./test.fq.gz -n 100 --species_id Bacteroides_vulgatus_57955

======================================================================
FAIL: test_help_text (__main__.RunSNPs)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_midas.py", line 113, in test_help_text
    self.assertTrue(run(self.command)==0, msg=error)
AssertionError:

Failed to execute the command: run_midas.py snps ./sample -1 ./test.fq.gz -n 100 --species_id Bacteroides_vulgatus_57955

======================================================================
FAIL: test_help_text (__main__.RunSpecies)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_midas.py", line 97, in test_help_text
    self.assertTrue(run(self.command)==0, msg=error)
AssertionError:

Failed to execute the command: run_midas.py species ./sample -1 ./test.fq.gz -n 100

----------------------------------------------------------------------
Ran 10 tests in 6.963s

FAILED (failures=6)

**Comment by snayfach** [comment]
Yes, I just released a new version a few weeks ago. Please try running the test with that version. You can check out what changed on the release notes.

Thanks,
Stephen
