### ISSUE TITLE
test_midas.py errors

### ISSUE THREAD

**Issue by ewilbanks** [snayfach/MIDAS#52]
Hi Stephen,

We ran test_midas.py and got the error output attached.  Any thoughts? 

We're testing run_midas.py species on some of our data now and it seems to be running just fine so far.  Think we need to be concerned out this testing error?

Thanks!
Lizzy
[test-midas-err.txt](https://github.com/snayfach/MIDAS/files/966759/test-midas-err.txt)

**Comment by snayfach** [comment]
Hi Lizzy,

I updated the tests so now the errors should be more informative:
```
cd /path/to/MIDAS
git pull
cd test
python test_midas.py
```

But if you are able to run the midas commands, then everything is probably OK.

**Comment by ewilbanks** [comment]
OK thanks!
