### ISSUE TITLE
changing the representative genome

### ISSUE THREAD

**Issue by ngarud** [snayfach/MIDAS#54]
Hi Stephen,

I want to change the representative genome used for calling SNPs for one of the species. I just wanted to confirm that the only two files that need to be updated using info from PATRIC are:

midas_db_v1.2/rep_genomes/Bacteroides_uniformis_57318/genome.features.gz
midas_db_v1.2/rep_genomes/Bacteroides_uniformis_57318/genome.fna.gz

Does midas_db_v1.2/genome_info.txt need to be updated too?

Thanks,
Nandita

**Comment by snayfach** [comment]
Hi Nandita,

No, I don't think the genome_info.txt needs to be updated. Let me know if
you get any errors and I can help.

Thanks,
Stephen

**Comment by ngarud** [comment]
Thanks!

**Comment by ngarud** [comment]
One more question -- suppose I run the SNP calling module in MIDAS with the --species_id flag. Do the number of reads that map to the desired species change in contrast to when MIDAS is run with all species (i.e. --species_id flag is not used)? 

Thanks,
Nandita

**Comment by snayfach** [comment]
Probably a bit depending on how related the species are in the community. I wouldn't worry too much about it.

I did this this a while back. Specifically, I compared consensus trees built by MIDAS using --species_topn 1 to --species_topn 20 for one species. The phylogenetic placements were nearly identical.

**Comment by snayfach** [comment]
I'm closing this, but reopen if you run into any error in the code
