### ISSUE TITLE
test fails

### ISSUE THREAD

**Issue by spleonard1** [snayfach/MIDAS#56]
Banging my head against the wall for awhile...  python test_midas.py fails with the following message:
| => python test_midas.py 
.....F....
======================================================================
FAIL: test_help_text (__main__.MergeSNPs)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_midas.py", line 143, in test_help_text
    self.assertTrue(sum(self.retcodes)==0, msg=error)
AssertionError: 

Failed to execute the command: merge_midas.py snps 

----------------------------------------------------------------------
Ran 10 tests in 288.881s

FAILED (failures=1)

using a brew installed python, packages are current (numpy, pysam, biopython, pandas).  Mac OS X Sierra 10.12.5.  Any ideas?

**Comment by LovelornPig** [comment]
I have the same issue.

**Comment by surh** [comment]
I  also have   the same issue. Running the test_midas.py in verbose mode confirms that MergeSNPs is failing.

```sh
% python test_midas.py -v
test_dependencies (__main__.CheckEnv) ... ok
test_dependencies (__main__.CheckVersions) ... ok
test_help_text (__main__.HelpText) ... ok
test_dependencies (__main__.ImportDependencies) ... ok
test_help_text (__main__.MergeGenes) ... ok
test_help_text (__main__.MergeSNPs) ... FAIL
test_help_text (__main__.MergeSpecies) ... ok
test_help_text (__main__.RunGenes) ... ok
test_help_text (__main__.RunSNPs) ... ok
test_help_text (__main__.RunSpecies) ... ok

======================================================================
FAIL: test_help_text (__main__.MergeSNPs)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_midas.py", line 143, in test_help_text
    self.assertTrue(sum(self.retcodes)==0, msg=error)
AssertionError: 

Failed to execute the command: merge_midas.py snps 

----------------------------------------------------------------------
Ran 10 tests in 299.986s

FAILED (failures=1)
python test_midas.py -v  297.05s user 2.80s system 99% cpu 5:00.05 total
```
I am using a conda environment.

```
% conda list
# packages in environment at /home/sur/.conda/envs/python-midas:
#
bcftools                  1.4.1                         0    bioconda
biopython                 1.68                np113py27_0  
bzip2                     1.0.6                         3  
curl                      7.52.1                        0  
htslib                    1.4.1                         0    bioconda
libgcc                    5.2.0                         0  
mkl                       2017.0.1                      0  
numpy                     1.13.0                   py27_0  
openssl                   1.0.2l                        0  
pandas                    0.20.2              np113py27_0  
pip                       9.0.1                    py27_1  
pysam                     0.11.2.1                 py27_0    bioconda
python                    2.7.13                        0  
python-dateutil           2.6.0                    py27_0  
pytz                      2017.2                   py27_0  
readline                  6.2                           2  
samtools                  1.4.1                         0    bioconda
setuptools                27.2.0                   py27_0  
six                       1.10.0                   py27_0  
sqlite                    3.13.0                        0  
tk                        8.5.18                        0  
wheel                     0.29.0                   py27_0  
xz                        5.2.2                         1  
zlib                      1.2.8                         3 
```
After looking through some files it seems like it is due to the --all_samples option that was included in the test for merge_midas.py. That option does not exist in the current merge_midas.py script. This was changed in the most recent commit to the test_midas.py script (https://github.com/snayfach/MIDAS/commit/8cc671b084ee1d14fe425b3a2d35a1615f8482d4).

I manually tried the merge_midas.py command from the test/ directory by setting `--sample_depth 0` & `--fract_cov 0.0001` & `--site_depth 1` instead of --all_samples. It seems to work

```zsh
% merge_midas.py snps ./snps -i ./sample -t list --species_id Bacteroides_vulgatus_57955 --sample_depth 0 --fract_cov 0.0001 --site_depth 1 --max_sites 100 

MIDAS: Metagenomic Intra-species Diversity Analysis System
version 1.2.1; github.com/snayfach/MIDAS
Copyright (C) 2015-2016 Stephen Nayfach
Freely distributed under the GNU General Public License (GPLv3)

===========Parameters===========
Command: /modules/pkgs/MIDAS/1.2.1/scripts/merge_midas.py snps ./snps -i ./sample -t list --species_id Bacteroides_vulgatus_57955 --sample_depth 0 --fract_cov 0.0001 --site_depth 1 --max_sites 100
Script: merge_midas.py snps
Database: /home/sur/micropopgen/data/midas_db_v1.2
Input: ./sample
Input type: list
Output directory: ./snps
Species selection criteria:
  keep species ids: ['Bacteroides_vulgatus_57955']
Sample selection criteria:
  keep samples with >= 0.0 mean coverage across sites with non-zero coverage
  keep samples where >= 0.01 percent of sites have non-zero coverage
Site selection criteria:
  keep sites covered by >= 1 reads across >= 95.0 percent of samples
  keep <= 100 sites
Number of CPUs to use: 1
===============================

Identifying species
  found 1 species with sufficient high-coverage samples

Merging snps
```
However the output files are empty. I am not sure it is a problem, it probably has to due with the fact that there is only one read per SNP in the few reads analyzed.

```zsh
% cat snps/Bacteroides_vulgatus_57955/snps_info.txt
site_id	mean_freq	mean_depth	site_prev	allele_props	site_type	gene_id	amino_acids	snps
% 
```

**Comment by snayfach** [comment]
Thanks @surh for tracking down the problem. I will specify the `-v` option in the future.

In the future if the tests are failing, I would recommend following the [tutorial](https://github.com/snayfach/MIDAS/blob/master/docs/tutorial.md#tutorial). This will help to track down the issue (if there is one at at). If there are no errors then it's the testing code itself with the problem.

I will release a new version of the code in the next week or two that addresses this issue and includes many other improvements.

**Comment by snayfach** [comment]
I've published a new release. Let me know if this does not solve the issue for you.

Thanks,
Stephen

**Comment by surh** [comment]
This solves the issue. Tests work in this release.

Thanks!

**Comment by snayfach** [comment]
Great! I'm closing this issue, but reopen if the problem appears again.
