### ISSUE TITLE
snps.py 

### ISSUE THREAD

**Issue by olga216** [snayfach/MIDAS#57]
Dear Snayfach

Thank you for your very useful tool. I was working with MIDAS trying to do a custom database. After several  attempts I got it. Now, I am running  "run_midas.py" using my custom database, however, I got a error and the output is wrong. This is the commands that I am using: 
run_midas.py snps MIDAS_outdir -1 R1.fastq -2 R2.fastq -d My_Database \
I was wondering if something is wrong with my custom database, because when the midasdb is used the output is correct and there is not error. Another possible cause of the error could be that something is happening with "mpileup" Do you have an idea about this issue?  Thanks. 

MIDAS: Metagenomic Intra-species Diversity Analysis System
version 1.2.1; github.com/snayfach/MIDAS
Copyright (C) 2015-2016 Stephen Nayfach
Freely distributed under the GNU General Public License (GPLv3)

===========Parameters===========
Command: MIDAS-1.2.2/scripts/run_midas.py snps MIDAS_outdir -1 R1.fastq -2 R2.fastq -d My_Database
Script: run_midas.py snps
Database: My_Database
Output directory: MIDAS_outdir
Remove temporary files: False
Pipeline options:
  build bowtie2 database of genomes
  align reads to bowtie2 genome database
  use samtools to generate pileups and call SNPs
Database options:
  include all species with >=3.0X genome coverage
Read alignment options:
  input reads (1st mate): R1.fastq
  input reads (2nd mate): R2.fastq
  alignment speed/sensitivity: very-sensitive
  number of reads to use from input: use all
  number of threads for database search: 1
SNP calling options:
  minimum alignment percent identity: 94.0
  minimum mapping quality score: 20
  minimum base quality score: 30
  minimum read quality score: 20
  trim 0 base-pairs from 3'/right end of read
================================

Reading reference data
  0.01 minutes
  0.05 Gb maximum memory

Building database of representative genomes
  total genomes: 5
  total contigs: 860
  total base-pairs: 25344819
  0.76 minutes
  0.22 Gb maximum memory

Mapping reads to representative genomes
  finished aligning
  checking bamfile integrity
  52.42 minutes
  0.88 Gb maximum memory

Running mpileup
  3.96 minutes
  0.88 Gb maximum memory

Formatting output
Traceback (most recent call last):
  File "/MIDAS-1.2.2/scripts/run_midas.py", line 699, in <module>
    run_program(program, args)
  File "/MIDAS-1.2.2/scripts/run_midas.py", line 81, in run_program
    snps.run_pipeline(args)
  File "/MIDAS3/MIDAS-1.2.2/midas/run/snps.py", line 295, in run_pipeline
    format_pileup(args, species, contigs)
  File "/MIDAS-1.2.2/midas/run/snps.py", line 126, in format_pileup
    contig = contigs[sp.contigs[sp.i]]
IndexError: list index out of range

**Comment by snayfach** [comment]
Hi Olga,

This bug is fixed in the latest version of MIDAS which you can obtain using `git clone https://github.com/snayfach/MIDAS`. Please let me know if this does not fix the issue.

Best,
Stephen

**Comment by snayfach** [comment]
So this may still be an issue with the newer version when there are very few mapped reads to the representative genome of a species. I am working on a solution now.

**Comment by nicoTR** [comment]
Hi!

I jump on the discussion cause I am working with Olga. For now, the issue is that if we followed the pipeline with our custom DB (1- run_midas.py species and run_midas.py snps,  merge_midas.py snps didn't work. If we rerun step 1 with the --species_id flag, then it worked for one of the species in our custom DB but not for the other). The error message is always the same, so basically the "Found 0 species with enough coverage" but if you have a look on the snaps output you find the species output for snps generated and if you decompress the file, you have a valid output. 
The custom DB is composed of 2 species that are dominant in the samples studied. 

Thanks for your help,

Nico

**Comment by snayfach** [comment]
Could you post the command you used and error received?

**Comment by nicoTR** [comment]
If all these steps are not done, then the error message is "Found 0 species with enough coverage" after step 2. When I used MIDAS db, after step 2 I can use merge_midas.py snps without any problem. But with our custom DB we have to add an extra step. 

-Step 1
 
run_midas.py species MIDAS_10_04_08_08_2 -1 HI.3741.001.Index_10.04-08-08-st2_R1.fastq -2 HI.3741.001.Index_10.04-08-08-st2_R2.fastq -d Database_Out_M_D

-Step 2

run_midas.py snps MIDAS_10_04_08_08_2 -1 HI.3741.001.Index_10.04-08-08-st2_R1.fastq -2 HI.3741.001.Index_10.04-08-08-st2_R2.fastq -d Database_Out_M_D

run_midas.py snps MIDAS_10_04_08_08_2 -1 HI.3741.001.Index_10.04-08-08-st2_R1.fastq -2 HI.3741.001.Index_10.04-08-08-st2_R2.fastq -d Database_Out_M_D

MIDAS: Metagenomic Intra-species Diversity Analysis System
version 1.2.1; github.com/snayfach/MIDAS
Copyright (C) 2015-2016 Stephen Nayfach
Freely distributed under the GNU General Public License (GPLv3)

===========Parameters===========
Command: scripts/run_midas.py snps MIDAS_10_04_08_08_2 -1 HI.3741.001.Index_10.04-08-08-st2_R1.fastq -2 HI.3741.001.Index_10.04-08-08-st2_R2.fastq -d Database_Out_M_D
Script: run_midas.py snps
Database: Database_Out_M_D
Output directory: MIDAS_10_04_08_08_2
Remove temporary files: False
Pipeline options:
  build bowtie2 database of genomes
  align reads to bowtie2 genome database
  use samtools to generate pileups and call SNPs
Database options:
  include all species with >=3.0X genome coverage
Read alignment options:
  input reads (1st mate): HI.3741.001.Index_10.04-08-08-st2_R1.fastq
  input reads (2nd mate): HI.3741.001.Index_10.04-08-08-st2_R2.fastq
  alignment speed/sensitivity: very-sensitive
  number of reads to use from input: use all
  number of threads for database search: 1
SNP calling options:
  minimum alignment percent identity: 94.0
  minimum mapping quality score: 20
  minimum base quality score: 30
  minimum read quality score: 20
  trim 0 base-pairs from 3'/right end of read
================================

Reading reference data
  0.01 minutes
  0.03 Gb maximum memory

Building database of representative genomes
  total genomes: 2
  total contigs: 409
  total base-pairs: 9121438
  0.16 minutes
  0.16 Gb maximum memory

Mapping reads to representative genomes
  finished aligning
  checking bamfile integrity
  29.68 minutes
  0.85 Gb maximum memory

Running mpileup
  3.67 minutes
  0.85 Gb maximum memory

Formatting output
Traceback (most recent call last):
  File "scripts/run_midas.py", line 699, in <module>
    run_program(program, args)
  File "scripts/run_midas.py", line 81, in run_program
    snps.run_pipeline(args)
  File "midas/run/snps.py", line 295, in run_pipeline
    format_pileup(args, species, contigs)
  File "midas/run/snps.py", line 126, in format_pileup
    contig = contigs[sp.contigs[sp.i]]
IndexError: list index out of range

-Step 3
run_midas.py snps MIDAS_10_04_08_08_2 -1 HI.3741.001.Index_10.04-08-08-st2_R1.fastq -2 HI.3741.001.Index_10.04-08-08-st2_R2.fastq -d Database_Out_M_D --species_id Microcystis_flosaquae

run_midas.py snps MIDAS_10_04_08_08_2 -1 HI.3741.001.Index_10.04-08-08-st2_R1.fastq -2 HI.3741.001.Index_10.04-08-08-st2_R2.fastq -d Database_Out_M_D --species_id Microcystis_flosaquae

MIDAS: Metagenomic Intra-species Diversity Analysis System
version 1.2.1; github.com/snayfach/MIDAS
Copyright (C) 2015-2016 Stephen Nayfach
Freely distributed under the GNU General Public License (GPLv3)

===========Parameters===========
Command: scripts/run_midas.py snps MIDAS_10_04_08_08_2 -1 HI.3741.001.Index_10.04-08-08-st2_R1.fastq -2 HI.3741.001.Index_10.04-08-08-st2_R2.fastq -d Database_Out_M_D --species_id Microcystis_flosaquae
Script: run_midas.py snps
Database: Database_Out_M_D
Output directory: MIDAS_10_04_08_08_2
Remove temporary files: False
Pipeline options:
  build bowtie2 database of genomes
  align reads to bowtie2 genome database
  use samtools to generate pileups and call SNPs
Database options:
  include specified species id(s): ['Microcystis_flosaquae']
Read alignment options:
  input reads (1st mate): HI.3741.001.Index_10.04-08-08-st2_R1.fastq
  input reads (2nd mate): HI.3741.001.Index_10.04-08-08-st2_R2.fastq
  alignment speed/sensitivity: very-sensitive
  number of reads to use from input: use all
  number of threads for database search: 1
SNP calling options:
  minimum alignment percent identity: 94.0
  minimum mapping quality score: 20
  minimum base quality score: 30
  minimum read quality score: 20
  trim 0 base-pairs from 3'/right end of read
================================

Reading reference data
  0.0 minutes
  0.03 Gb maximum memory

Building database of representative genomes
  total genomes: 1
  total contigs: 288
  total base-pairs: 4675790
  0.08 minutes
  0.14 Gb maximum memory

Mapping reads to representative genomes
  finished aligning
  checking bamfile integrity
  26.37 minutes
  0.85 Gb maximum memory

Running mpileup
  3.06 minutes
  0.85 Gb maximum memory

Formatting output
  8.08 minutes
  0.85 Gb maximum memory


-Step 4

merge_midas.py snps outdir_1 -i MIDAS_10_04_08_08_2,MIDAS_10_04_08_08_3 -t list -d Database_Out_M_D

Command: scripts/merge_midas.py snps outdir_1 -i MIDAS_10_04_08_08_2,MIDAS_10_04_08_08_3 -t list -d Database_Out_M_D
Script: merge_midas.py snps
Database: Database_Out_M_D
Input: MIDAS_10_04_08_08_2,MIDAS_10_04_08_08_3
Input type: list
Output directory: outdir_1
Species selection criteria:
  keep species with >= 1 samples
Sample selection criteria:
  keep samples with >= 5.0 mean coverage across sites with non-zero coverage
  keep samples where >= 40.0 percent of sites have non-zero coverage
Site selection criteria:
  keep sites covered by >= 3 reads across >= 95.0 percent of samples
Number of CPUs to use: 1
===============================

Identifying species
  found 1 species with sufficient high-coverage samples

Merging snps

**Comment by snayfach** [comment]
Right, so it looks like the species you're interested in is present at <3x
depth in the metagenome based on the reads mapped to its marker genes. You
can confirm this by looking at the file `
MIDAS_10_04_08_08_2/species/species_profile.txt`.

Since you know what species you're interested in, you can actually skip the
`run_midas.py species` step all together. Instead, just specify one or more
species using the `--species_id` flag when you run `run_midas.py snps` or
`run_midas.py genes`. After than, you can run `merge_midas.py snps` or `
merge_midas.py genes`

**Comment by nicoTR** [comment]
That is weird cause for example for the sample 10_04_08_08_2 I have:
species_id	count_reads	coverage	relative_abundance
Microcystis_flosaquae	2724	33.1954744817	0.861279164952

What we found with Olga, is that we need to follow step 1,2,3 and 4 if not some files apparently are missing and the merge_midas.py snps just gave Found 0 species with enough coverage. But if we followed these steps, then merge_midas.py snps worked. 

Could I send you the custom DB that we are using?

**Comment by snayfach** [comment]
No that's OK. I understand what is happening. The error you're seeing is due to a bug in the code. It has been fixed on the dev branch, but I haven't pushed it to the master branch yet. I aim to have a new release with the bug fixed in the next day or two. Thanks for your patience.

**Comment by nicoTR** [comment]
Ok great, thanks!

**Comment by snayfach** [comment]
I've published a new release. Please let me know if this does not solve the issue for you.

**Comment by nicoTR** [comment]
When I run the test I have : 
FAIL: test_class (__main__._15_BuildDB)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_midas.py", line 152, in test_class
    self.assertTrue(code==0, msg=err)
AssertionError: 
Error: program 'vsearch' not found in your PATH
Make sure that you've installed the program and added it's location to your PATH

But I have well installed the dependancies (Finished processing dependencies for MIDAS==1.3.0) and I have specified the path as usual.

**Comment by snayfach** [comment]
That's OK. You need vsearch and HMMER in your PATH to build a custom db. Everything else works

**Comment by nicoTR** [comment]
Hi!

Well now I got a new error that I never got before using custom DB. 

Identifying species and samples
Traceback (most recent call last):
  File "/home/nico/Desktop/programmes/MIDAS/scripts/merge_midas.py", line 441, in <module>
    run_program(program, args)
  File "/home/nico/Desktop/programmes/MIDAS/scripts/merge_midas.py", line 431, in run_program
    snps.run_pipeline(args)
  File "/home/nico/Desktop/programmes/MIDAS/midas/merge/snps.py", line 474, in run_pipeline
    species_list = merge.select_species(args, dtype='snps')
  File "/home/nico/Desktop/programmes/MIDAS/midas/merge/merge.py", line 161, in select_species
    species = init_species(samples, args, dtype)
  File "/home/nico/Desktop/programmes/MIDAS/midas/merge/merge.py", line 130, in init_species
    genome_info = read_genome_info(args['db'])
  File "/home/nico/Desktop/programmes/MIDAS/midas/merge/merge.py", line 100, in read_genome_info
    for r in csv.DictReader(open(path), delimiter='\t'):
IOError: [Errno 2] No such file or directory: '/mnt/Xtra/Nico/Reads_Long_term_trimmed/Database_Out_M_D/genome_info.txt'

I have no idea why that file 'genome_info.txt' is not generated...

Thanks!

Nico

**Comment by snayfach** [comment]
Hi Nico. You need to re-build the custom database with the new version of the code.

**Comment by nicoTR** [comment]
Thanks! I am redoing the analysis right now...Will keep you informed!

**Comment by nicoTR** [comment]
Hi!

So now it worked perfectly thanks! Last question for you, I always got this message "0 sample pairs processed" after using strain_tracking.py track_markers, my interpretation is that there is no rare SNPs that can be tracked. Am I correct?
Thanks!
Nico

**Comment by snayfach** [comment]
Hi Nico,

When you run `merge_midas.py snps`, MIDAS uses the flag `--core_snps` by default. This means that only SNPs present at >1% allele frequency in the pooled data are reported in the output files (the actual frequency is determined by `--allele_freq`). Sample-specific variants may be present at <1% allele frequency if you have many samples. To include these variants as well, you should run `merge_midas.py snps` using the flag `--core_sites`.

**Comment by snayfach** [comment]
I'm closing this issue since there has been no comment for several months. Please reopen as needed

**Comment by drish91** [comment]
Just a quick edit.
Documentation explanation says to use "--core-sites" (hyphen) instead of "--core_sites" (underscore).
It's confusing if you don't look at the script to see what each of those flags mean.
It'd be great if you could fix that!

-Drishti
