### ISSUE TITLE
No output or errors in snps and genes modes

### ISSUE THREAD

**Issue by sharrax** [snayfach/MIDAS#63]
Hello, dear colleagues! Thank you for this amazing tool!

However, I'm having an issue of not getting any output when I run snps and genes modes. In both snps and genes folders there are empty output folders and the size of snps/temp/pangenomes.bam is 0 bytes. Species module works just fine - we obtained species_profile.txt on every sample.

Below you will find a log I got while running genes module on one of the samples. Thanks in advance!

MIDAS: Metagenomic Intra-species Diversity Analysis System
version 1.3.0; github.com/snayfach/MIDAS
Copyright (C) 2015-2016 Stephen Nayfach
Freely distributed under the GNU General Public License (GPLv3)

===========Parameters===========
Command: /home/samoilov/MIDAS/scripts/run_midas.py genes -1 /data5/bio/runs-nprian/pipeline-results/illumina/qc_intermediate/Hp_23_S25_R1.trim.nohum.fastq.gz -2 /data5/bio/runs-nprian/pipeline-results/illumina/qc_intermediate/Hp_23_S25_R2.trim.nohum.fastq.gz -t 20 /data7/bio/runs-samoilov/MIDAS/Hp_23_S25
Script: run_midas.py genes
Database: /data7/bio/BacGenomeSoft/MIDAS_DB/midas_db_v1.2
Output directory: /data7/bio/runs-samoilov/MIDAS/Hp_23_S25
Remove temporary files: False
Pipeline options:
  build bowtie2 database of pangenomes
  align reads to bowtie2 pangenome database
  quantify coverage of pangenomes genes
Database options:
  include all species with >=3.0X genome coverage
Read alignment options:
  input reads (1st mate): /data5/bio/runs-nprian/pipeline-results/illumina/qc_intermediate/Hp_23_S25_R1.trim.nohum.fastq.gz
  input reads (2nd mate): /data5/bio/runs-nprian/pipeline-results/illumina/qc_intermediate/Hp_23_S25_R2.trim.nohum.fastq.gz
  alignment speed/sensitivity: very-sensitive
  number of reads to use from input: use all
  number of threads for database search: 20
Gene coverage options:
  minimum alignment percent identity: 94.0
  minimum alignment coverage of reads: 0.75
  minimum read quality score: 20
  minimum mapping quality score: 0
  trim 0 base-pairs from 3'/right end of read
================================

Building pangenome database
command: /home/samoilov/MIDAS/bin/Linux/bowtie2-build --threads 20 /data7/bio/runs-samoilov/MIDAS/Hp_23_S25/genes/temp/pangenomes.fa /data7/bio/runs-samoilov/MIDAS/Hp_23_S25/genes/temp/pangenomes 

Aligning reads to pangenomes
command: /home/samoilov/MIDAS/bin/Linux/bowtie2 --no-unal -x /data7/bio/runs-samoilov/MIDAS/Hp_23_S25/genes/temp/pangenomes --very-sensitive-local --threads 20 -q -1 /data5/bio/runs-nprian/pipeline-results/illumina/qc_intermediate/Hp_23_S25_R1.trim.nohum.fastq.gz -2 /data5/bio/runs-nprian/pipeline-results/illumina/qc_intermediate/Hp_23_S25_R2.trim.nohum.fastq.gz | /home/samoilov/MIDAS/bin/Linux/samtools view --threads 20 -b - > /data7/bio/runs-samoilov/MIDAS/Hp_23_S25/genes/temp/pangenomes.bam

**Comment by snayfach** [comment]
Hi sharrax,

It looks like the log file is missing some important information. Would you mind rerunning the command and sending me the full standard output from MIDAS? Also, are you running MIDAS on a Mac or a unix server?

Thanks,
Stephen

**Comment by snayfach** [comment]
Closing this issue due to no response from user
