### ISSUE TITLE
test.py issue

### ISSUE THREAD

**Issue by CTraverse** [snayfach/MIDAS#71]
Hello, I'm trying to test MIDAS and I keep getting the following error when I run the test_midas.py script:
python test_midas.py -vf
test_class (__main__._01_CheckEnv) ... ok
test_class (__main__._02_ImportDependencies) ... ok
test_class (__main__._03_CheckVersions) ... ok
test_class (__main__._04_HelpText) ... FAIL

======================================================================
FAIL: test_class (__main__._04_HelpText)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_midas.py", line 84, in test_class
    self.assertTrue(code==0, msg=err)
AssertionError: False is not true : b'Traceback (most recent call last):\n  File "/home1/02661/traverse/build/MIDAS/scripts/run_midas.py", line 8, in <module>\n    from midas import utility\n  File "/home1/02661/traverse/build/MIDAS/midas/utility.py", line 7, in <module>\n    import io, os, stat, sys, resource, gzip, platform, subprocess, bz2, Bio.SeqIO\nImportError: No module named Bio.SeqIO\n'

----------------------------------------------------------------------
Ran 4 tests in 0.518s

FAILED (failures=1)

I have all of the dependencies installed and they work properly when I import them in a python environment. I'm using python3, which might be the issue. Is MIDAS compatible with python3? I tried using 2.7 but I couldn't properly install the dependencies on the cluster I'm using.

**Comment by snayfach** [comment]
It looks like Biopython is not installed or your PYTHONPATH is not updated. What happens when you open a python terminal and enter `import Bio.SeqIO`?

**Comment by CTraverse** [comment]
import Bio.SeqIO works just fine in a python terminal.

**Comment by snayfach** [comment]
When you open a python terminal, is it python2 or python3? Is Biopython installed under python2 or python3?

**Comment by CTraverse** [comment]
Biopython is installed under python3. I added alias python=python3 in .bashrc to ensure there wouldn't be any python2 without explicitly stating python2. python --version gives python 3.4

**Comment by snayfach** [comment]
Weird. Maybe try installing under python2 and giving the test another go. I've never seen this issue before.

**Comment by CTraverse** [comment]
I just installed python2.7 and installed the dependencies. They all import correctly in a python2.7 terminal. I ran the test_midas.py script and I'm getting a new error.
`python test_midas.py -vf
test_class (__main__._01_CheckEnv) ... ok
test_class (__main__._02_ImportDependencies) ... ok
test_class (__main__._03_CheckVersions) ... ok
test_class (__main__._04_HelpText) ... ok
test_class (__main__._05_RunSpecies) ... ok
test_class (__main__._06_RunGenes) ... FAIL

======================================================================
FAIL: test_class (__main__._06_RunGenes)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_midas.py", line 96, in test_class
    self.assertTrue(code==0, msg=err)
AssertionError:
Error encountered executing:
/home1/02661/traverse/build/MIDAS/bin/Linux/bowtie2 --no-unal -x ./sample/genes/temp/pangenomes -u 100 --very-sensitive-local --threads 1 -q -U ./test.fq.gz | /home1/02661/traverse/build/MIDAS/bin/Linux/samtools view --threads 1 -b - > ./sample/genes/temp/pangenomes.bam

Error message:
/home1/02661/traverse/build/MIDAS/bin/Linux/samtools: error while loading shared libraries: libbz2.so.1.0: cannot open shared object file: No such file or directory
Warning: gzbuffer added in zlib v1.2.3.5. Unable to change buffer size from default of 8192.
100 reads; of these:
  100 (100.00%) were unpaired; of these:
    45 (45.00%) aligned 0 times
    11 (11.00%) aligned exactly 1 time
    44 (44.00%) aligned >1 times
55.00% overall alignment rate




----------------------------------------------------------------------
Ran 6 tests in 33.917s

FAILED (failures=1)`

**Comment by snayfach** [comment]
OK, so this is a known issue with the binaries included with the code. They work on my system, but not other systems with older versions of certain shared libraries. To address this issue, you'll need to install Bowtie2 and Samtools and create symbolic links to the new binaries. This solution is detailed in issue #69 here: https://github.com/snayfach/MIDAS/issues/69

I plan to address this issue more formally in the future

**Comment by CTraverse** [comment]
Thank you for your help and quick responses. I'll work on addressing that ussue

**Comment by snayfach** [comment]
I've fixed this issue in the latest release. If the problem persists please reopen this issue
