### ISSUE TITLE
test_midas.py issue with bowtie2 and samtools binaries

### ISSUE THREAD

**Issue by tamburinif** [snayfach/MIDAS#72]
I recently attempted to install MIDAS on our Linux cluster. When I tested the installation ('test_midas.py -vf'), I encountered the following issue in which the test script would fail on the RunGenes step:

```
[04:10:26] scg4-ln02:~/fiona/tools/MIDAS $ python test/test_midas.py -vf
test_class (__main__._01_CheckEnv) ... ok
test_class (__main__._02_ImportDependencies) ... ok
test_class (__main__._03_CheckVersions) ... ok
test_class (__main__._04_HelpText) ... ok
test_class (__main__._05_RunSpecies) ... ok
test_class (__main__._06_RunGenes) ... FAIL

======================================================================
FAIL: test_class (__main__._06_RunGenes)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/test_midas.py", line 96, in test_class
    self.assertTrue(code==0, msg=err)
AssertionError: 
Error encountered executing:
/home/tamburin/fiona/tools/MIDAS/bin/Linux/bowtie2 --no-unal -x ./sample/genes/temp/pangenomes -u 100 --very-sensitive-local --threads 1 -q -U ./test.fq.gz | /home/tamburin/fiona/tools/MIDAS/bin/Linux/samtools view --threads 1 -b - > ./sample/genes/temp/pangenomes.bam

Error message:
/home/tamburin/fiona/tools/MIDAS/bin/Linux/samtools: error while loading shared libraries: libbz2.so.1.0: cannot open shared object file: No such file or directory
/home/tamburin/fiona/tools/MIDAS/bin/Linux/bowtie2-align-s: symbol lookup error: /home/tamburin/fiona/tools/MIDAS/bin/Linux/bowtie2-align-s: undefined symbol: gzopen64
(ERR): bowtie2-align exited with value 127




----------------------------------------------------------------------
Ran 6 tests in 64.456s

FAILED (failures=1)

```

I was eventually able to fix this by removing the included samtools and bowtie2 binaries and replacing them with symlinks to the installations on our cluster. If others are experiencing same error, it appears that installing your own versions is a workaround. It would be helpful for the developers to look into why this is happening and create a fix.

**Comment by casimonet** [comment]
Hi, I am having the same issue. I tried to do the same but it seems I am not setting up the symlinks correctly. I'm new at bioinformatics so not sure of what I am doing.
Can I ask you how did you do this? So far here is what I have done:

Once MIDAS is downloaded:

`rm ./MIDAS/bin/Linux/samtools`
`rm ./MIDAS/bin/Linux/bowtie2`

`ln -s /exports/applications/.../apps/samtools/1.6   ./MIDAS/bin/Linux/samtools`
`ln -s /exports/applications/.../apps/bowtie/2.2.6   ./MIDAS/bin/Linux/bowtie2`

`python MIDAS/setup.py install`

But then I get the following error:

`Error: File not executable: ./MIDAS/bin/Linux/samtools
`
Thank you,
Camille

**Comment by snayfach** [comment]
I intend to fix this issue.

In the meantime, try making the links executable:
`chmod +x MIDAS/bin/Linux/samtools`
`chmod +x MIDAS/bin/Linux/bowtie2`

**Comment by snayfach** [comment]
I've fixed this issue in the latest release. If the problem persists please reopen this issue
