### ISSUE TITLE
RunSNPs test error

### ISSUE THREAD

**Issue by snurk** [snayfach/MIDAS#74]
Hello!

I am getting a weird error on RunSNPs test.
Error log is attached.
Do you have any suggestions?
[error.log](https://github.com/snayfach/MIDAS/files/1507082/error.log)

**Comment by snayfach** [comment]
I'm guessing it's related to your python version. To confirm, could you try with python 2.7?

**Comment by snurk** [comment]
It worked!
Thank you very much for your prompt reply, will use python 2 for now.
