### ISSUE TITLE
RunSpecies fail during test, could not execute bowtie2 binary

### ISSUE THREAD

**Issue by xsharkbaitx** [snayfach/MIDAS#76]
Trying to set up MIDAS on a server running CentOS with updated version of bowtie2 (2.3.2) on the server.  Can't get past this failure.  

[~]$ ./test_midas.py -vf
test_class (__main__._01_CheckEnv) ... ok
test_class (__main__._02_ImportDependencies) ... ok
test_class (__main__._03_CheckVersions) ... ok
test_class (__main__._04_HelpText) ... ok
test_class (__main__._05_RunSpecies) ... FAIL

======================================================================
FAIL: test_class (__main__._05_RunSpecies)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./test_midas.py", line 90, in test_class
    self.assertTrue(code==0, msg=err)
AssertionError:
Error: could not execute bowtie2 binary: /~/MIDAS/bin/Linux/bowtie2
(exited with error code 127)
To solve this issue, follow these steps:
  1) Go to https://sourceforge.net/projects/bowtie-bio/files/bowtie2/2.3.2
  2) Download bowtie2-2.3.2-linux-x86_64.zip
  3) Unpack the software on your system
  4) Copy the new bowtie2 binaries to: /usr/local/genome/bin/MIDAS/bin/Linux

----------------------------------------------------------------------
Ran 5 tests in 2.078s

FAILED (failures=1)

**Comment by snayfach** [comment]
What happens when you try and run the binary from the command line:

/usr/local/genome/bin/MIDAS/bin/Linux/bowtie2 -h

**Comment by xsharkbaitx** [comment]
This is the error message I receive:
[cchabot@grendel Linux]$ ./bowtie2 -h
/usr/local/genome/bin/MIDAS/bin/Linux/bowtie2-align-s: error while loading shared libraries: libtbb.so.2: cannot open shared object file: No such file or directory
(ERR): Description of arguments failed!
Exiting now ...

**Comment by snayfach** [comment]
You need to follow these directions:

   1. Go to https://sourceforge.net/projects/bowtie-bio/files/bowtie2/2.3.2
   2. Download bowtie2-2.3.2-linux-x86_64.zip
   3. Unpack the software on your system
   4. Copy the new bowtie2 binaries to: /usr/local/genome/bin/MIDAS/
   bin/Linux

Or you could probably create symbolic links to your working version of
bowtie2 and place them in /usr/local/genome/bin/MIDAS/bin/Linux

Thanks,
Stephen

**Comment by xsharkbaitx** [comment]
Thanks for your help on this.  We were able to get it running after downloading the legacy version of Bowtie2 and replacing the provided version of Bowtie2 with it.  Tests all passed with the exception of search not found (as expected as we don't have it).
