### ISSUE TITLE
Deduplication and alleles frequency estimation with strain stracking pipelines

### ISSUE THREAD

**Issue by casimonet** [snayfach/MIDAS#82]
Hi,

I am realtively new to this kind of data so my question might be naive. I am extensively using the MIDAS pipeline for my project and I came to wonder how the deduplication step when dealing with raw sequencing data (gut metagenomes) could affect our ability to accurately estimate alleles frequency.
There are a bunch of strain tracking pipeline similar to MIDAS coming out but I don't think I have seen this issue being explored by any of them (althgouh I have not read those other papers in details yet).

I do not have a strong intuition about how this could affect it but an accurate allele frequency estimation relies on having one read per original DNA molecule right ('one genome per bacteria').
How big could the issue be and should this be check by simulations or something?

Thanks,
Camille

**Comment by snayfach** [comment]
Hi Camille,

Thanks for your question. I agree that deduplicating reads could be a problem for accurately quantifying allele frequencies, which is why I would recommend not deduplicating. That's also the recommendation from this [paper](https://doi.org/10.1016/j.cell.2016.08.007).

Thanks,
Stephen

**Comment by casimonet** [comment]
Ok, thanks!

Best,
Camille
