### ISSUE TITLE
non-synonymous sites

### ISSUE THREAD

**Issue by palomo11** [snayfach/MIDAS#87]
Hi,

I have a doubt when using snp_diversity.py. I want to quantify diversity at non-synonymous sites, based on the example in the tutorial:

```
snp_diversity.py /path/to/snps --genomic_type genome-wide --sample_type pooled-samples --site_type 4D --locus_type CDS --out /path/to/output
```

I should use --site_type 4D, but in the description of the different option it says:

```
--site_type {1D,2D,3D,4D}
if locus_type == 'CDS', use genomic sites with specified degeneracy: 4D indicates synonymous and 1D non-synonymous sites
```

So to quantify diversity at non-synonymous sites,  should it be use --site_type 4D or 1D?

**Comment by snayfach** [comment]
Good catch. Use 1D for non-syn and 4D for syn. I've updated the documentation

**Comment by palomo11** [comment]
OK, thanks.

By the way if I have several species across several samples is there any way to calculate the dN/dS using MIDAS?

Thanks in advance!

**Comment by snayfach** [comment]
No there's not, sorry
